### ISSUE TITLE
mysqldump not working with empty password

### ISSUE THREAD

**Issue by pirm-in** [getdave/grunt-deployments#11]
I had a testing setup where my mysql user on the development server had an empty/no password. The mysqldump function did not work in this case.

**Comment by getdave** [comment]
Thanks for the heads up. I really appreciate you taking the time to feedback.

**Comment by getdave** [comment]
This is probably a bit of an edge case. 

> mysql user on the development server had an empty/no password

@pirm-in Can you please confirm whether for the scenario above running `mysqldump` directly on your terminal using the `-p` flag causes an error? I'm trying to establish what command syntax is required by `mysqldump` if the password is empty/not set. Help appreciated.

**Comment by getdave** [comment]
No response. Closing as edge case
