### ISSUE TITLE
Mysqldump on remote target doesn't use Host option

### ISSUE THREAD

**Issue by alehlopeh** [getdave/grunt-deployments#14]
Some VPS (MediaTemple) don't use localhost as the mysql host. This causes the mysqldump to fail silently. An error is reported when importing to local db.

**Comment by getdave** [comment]
@alehlopeh Thanks for the bug report. I intend to put in place some more accurate procedures to guard against errors. If you have the output of the console handy and steps to reproduce that would be gratefully receieved.

**Comment by alehlopeh** [comment]
@getdave Here's the output I got. The remote server's db host is internal-db.xxxxxxxx.gridserver.com. 

```
▶ grunt db_pull --target="live"
Running "db_pull" task

Pulling database from 'Live' into Local
Creating DUMP of remote database
>> Database DUMP succesfully exported to:
>> db/live/20130923/17-17-08/db_backup.sql
Replacing 'http://xxxxxxx.org' with 'http://xxxxxxx.dev' in the database.
sed: 1: "s/http://xxxxxxx.org/ ...": bad flag in substitute command: 'f'
>> Database references succesfully updated.
Creating DUMP of local database
>> Database DUMP succesfully exported to:
>> db/local/20130923/17-17-08/db_backup.sql
Importing into local database
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '' at line 1
>> Database imported succesfully

Operations completed

Done, without errors.

▶ cat db/live/20130923/17-17-08/db_backup.sql
mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) when trying to connect

```

Despite saying it successfully exported the database, the resulting db_backup.sql file is empty except for an error message, which of course causes the subsequent import to fail as well. It turns out that config.host was not being passed to the template. I've fixed this and will send a pull request shortly.

**Comment by getdave** [comment]
@alehlopeh Thanks very much for the pull request. It's been merged in. Really appreciate your work on this.

I'm planning on integrating some automated tests into this Plugin repo so that we can catch more errors like this. 

I'm very aware that the task reports "Success" a lot, even when it fails (which is a bit misleading to say the least!). I am going to work on this very soon.
