### ISSUE TITLE
Sed error with URLs

### ISSUE THREAD

**Issue by darioghilardi** [getdave/grunt-deployments#17]
Hello,
I am getting a sed error when replacing database URLs. The problem is easy to understand, there's no escape for the URLs I have into the Gruntfile.js so the sed command will be:

```
sed -i '' 's/http://aaa.com/http//bbb.com/g' <%= path %>
```

This is a problem because the slash inside the command are not escaped and makes confusion on sed. A very quick fix should be the use of another sed delimiter, like `#`instead of `/`.

**Comment by getdave** [comment]
Should shortly be closed via release.
