### ISSUE TITLE
Ignore some tables

### ISSUE THREAD

**Issue by nicooprat** [getdave/grunt-deployments#24]
Hi. It would be great to be able to ignore some tables. For example, I've a Wordpress with the Relevanssi plugin installed, which is kind of a big search index;  it doesn't have any value for the developer and it's really slowing down the process.

I'd love something like :

```
options {
    ignoreTables: 'wp-relevanssi,[...]',
    ...
}
```

Do you think it's possible ?
Thanks.

**Comment by getdave** [comment]
@nicooprat Thanks for raising this. I think that's a great idea. We can achieve it via

http://dev.mysql.com/doc/refman/5.1/en/mysqldump.html#option_mysqldump_ignore-table

This one goes on the list! If you'd like to contribute please let me know.

**Comment by nicooprat** [comment]
Thanks ! I'd love to help, but I don't think I have the competences... I'll wait ;)

**Comment by getdave** [comment]
This feature has been added. 

Kudos to @nicooprat for the work.
