### ISSUE TITLE
Port to Gulp ?

### ISSUE THREAD

**Issue by nicooprat** [getdave/grunt-deployments#35]
Hi

Looks like [Gulp](http://gulpjs.com/) is gaining some interest these days. Could you be able to port your plugin ? It's the most useful to me, so until Gulp has something equivalent, I won't switch :)

Thanks.

**Comment by getdave** [comment]
Looks interesting. I've been watching Gulp but I don't think this Plugin will be ported to Gulp any time soon. I just don't have the time.

I'm looking to upgrade this Plugin (check out the feature branches on this repo) in the near future. Maybe once it's fully tested I could consider porting it.

**Comment by nicooprat** [comment]
Ok thanks I'll keep an eye on it !

**Comment by getdave** [comment]
Not going to happen any time soon I'm afraid. Closing for now.
