### ISSUE TITLE
Deploying with MAMP and cPanel (stdin is not a tty & Error 1064)

### ISSUE THREAD

**Issue by eriteric** [getdave/grunt-deployments#45]
Receiving error:
"Importing DUMP into remote database
stdin: is not a tty
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '/bin/sh: mysqldump: command not found' at line 1"

Any idea how to fix this? Much appreciated!

**Comment by eriteric** [comment]
I got rid of the "stdin: is not a tty" error, this seems to be exclusive to cpanel 
fixed by editing the etc/bashrc file. 
Comment out this line:

```
mesg y
```

and/or add:

```
if `tty -s`; then
 mesg n
fi
```

I'm still seeing this though:

```
Importing DUMP into remote database
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '/bin/sh: mysqldump: command not found' at line 1
>> Database imported succesfully
```

**Comment by eriteric** [comment]
Ok, sorry for the non-issue but perhaps this can help others.
I was using MAMP locally on OSX, and found that the local dump was not being performed correctly. This is because MAMP stores mysql in another directory. To fix, you can create a symlink like so:

```
sudo ln -s /Applications/MAMP/Library/bin/mysqldump /usr/local/bin/mysqldump
```

**Comment by getdave** [comment]
@eriteric No worries. I think your issues is similar to https://github.com/getdave/grunt-deployments/issues/37

Would you consider submitting a PR which creates a "Troubleshooting" section in the README and adds a note about ensuring you reference the correct `mysql`?

**Comment by eriteric** [comment]
you got it! pull request sent

**Comment by adampatarino** [comment]
@eriteric did you have to both create a symlink and comment out `mesg y` ? 
I've created the symlink and I am able to create local dumps, but I can't seem to push or pull without running into this error. Do I really have to modify the `bashrc` file on my servers?

**Comment by eriteric** [comment]
Sorry for extremely late reply. Hopefully you have resolved this :) but just in case anyone else is at the same spot: I had to do both of those on one server but could do with just one on another, so that's why I left it as and/or. Yes, editing the bashrc file is the only method of correction as far as I'm aware.
